import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['**/*.{test,spec}.{ts,tsx}'],
    environment: 'node',
    environmentMatchGlobs: [['**/*.test.tsx', 'jsdom']],
    globals: false,
    coverage: {
      provider: 'v8',
      include: [
        'lib/**/*.ts',
        'services/**/*.ts',
        'pages/ForgotPassword.tsx',
        'pages/ResetPassword.tsx',
        'pages/PaymentCallback.tsx',
        'pages/AdminInventory.tsx',
        'pages/AdminReports.tsx',
        'components/AIAssistant.tsx',
        'components/BlurredProduct.tsx',
        'components/Footer.tsx',
        'components/ProductCard.tsx',
        'components/Reviews.tsx',
        'components/NavBar.tsx',
        'components/ui/**/*.tsx',
        'contexts/ToastContext.tsx',
        'server/utils/authTokens.js',
        'server/utils/ensureDefaultAdmin.js',
        'server/utils/logger.js',
        'server/utils/notificationService.js',
        'server/utils/summaryScheduler.js',
        'server/middleware/auth.js',
        'server/middleware/adminCheck.js',
        'server/models/Message.js',
        'server/models/Order.js',
        'server/models/Product.js',
        'server/models/User.js',
        'server/scripts/seedData.js',
        'server/routes/supportRoutes.js',
        'server/routes/cartRoutes.js',
        'server/routes/paymentRoutes.js',
        'server/routes/messageRoutes.js',
        'server/routes/productRoutes.js',
      ],
      exclude: ['lib/**/*.test.ts', 'services/**/*.test.ts', 'pages/**/*.test.tsx', 'components/**/*.test.tsx', 'contexts/**/*.test.tsx', 'server/**/*.test.ts'],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 50,
        lines: 80,
      },
    },
  },
});
