import { Product, User, Order, Review, Conversation, Message, Dispute } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Mathematics Textbook',
    description: 'Complete Mathematics textbook for first year students. Covers calculus, algebra, and trigonometry.',
    price: 5000,
    category: 'Textbooks',
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'],
    seller: {
      id: '101',
      fullName: 'John Seller',
      email: 'seller@babcock.edu.ng',
      phone: '08012345678',
      role: 'seller',
      isVerified: true,
      ratings: 4.5,
    },
    condition: 'Like New',
    inStock: true,
    ratings: 4.5,
    reviews: [],
  },
  {
    id: '2',
    title: 'Laptop Stand',
    description: 'Adjustable aluminum laptop stand for better ergonomics. Fits all laptops up to 17 inches.',
    price: 3500,
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'],
    seller: {
      id: '101',
      fullName: 'John Seller',
      email: 'seller@babcock.edu.ng',
      phone: '08012345678',
      role: 'seller',
      isVerified: true,
      ratings: 4.5,
    },
    condition: 'Good',
    inStock: true,
    ratings: 4.0,
    reviews: [],
  },
  {
    id: '3',
    title: 'Bedding Set',
    description: 'Comfortable 3-piece bedding set includes fitted sheet, flat sheet, and pillowcases. Perfect for hostel.',
    price: 12000,
    category: 'Hostel Essentials',
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'],
    seller: {
      id: '101',
      fullName: 'John Seller',
      email: 'seller@babcock.edu.ng',
      phone: '08012345678',
      role: 'seller',
      isVerified: true,
      ratings: 4.5,
    },
    condition: 'New',
    inStock: true,
    ratings: 5.0,
    reviews: [],
  },
  {
    id: '4',
    title: 'Scientific Calculator',
    description: 'Casio FX-991ES Plus scientific calculator. Perfect for engineering and science students.',
    price: 4500,
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1587145820266-a5951ee6f620?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'],
    seller: {
      id: '102',
      fullName: 'Sarah Smith',
      email: 'sarah@babcock.edu.ng',
      phone: '08012345681',
      role: 'seller',
      isVerified: true,
      ratings: 4.8,
    },
    condition: 'Like New',
    inStock: true,
    ratings: 4.8,
    reviews: [],
  },
  {
    id: '5',
    title: 'Desk Lamp',
    description: 'LED desk lamp with adjustable brightness and USB charging port. Perfect for late-night studying.',
    price: 2800,
    category: 'Hostel Essentials',
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'],
    seller: {
      id: '103',
      fullName: 'Michael Chen',
      email: 'michael@babcock.edu.ng',
      phone: '08012345682',
      role: 'seller',
      isVerified: true,
      ratings: 4.3,
    },
    condition: 'Good',
    inStock: true,
    ratings: 4.3,
    reviews: [],
  },
  {
    id: '6',
    title: 'Water Bottle',
    description: 'Stainless steel insulated water bottle. Keeps drinks cold for 24 hours or hot for 12 hours.',
    price: 3200,
    category: 'Hostel Essentials',
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'],
    seller: {
      id: '104',
      fullName: 'Emma Wilson',
      email: 'emma@babcock.edu.ng',
      phone: '08012345683',
      role: 'seller',
      isVerified: true,
      ratings: 4.7,
    },
    condition: 'New',
    inStock: true,
    ratings: 4.7,
    reviews: [],
  },
];

export const MOCK_USER: User = {
  id: '1001',
  name: 'Jane Buyer',
  fullName: 'Jane Buyer',
  email: 'buyer@babcock.edu.ng',
  phone: '08012345680',
  role: 'user',
  isVerified: true,
  avatar: 'https://placehold.co/150x150/e2e8f0/1e293b?text=JB',
  profileImage: 'https://placehold.co/150x150/e2e8f0/1e293b?text=JB',
  ratings: 4.2,
};

export const MOCK_ADMIN: User = {
  id: '1002',
  name: 'Admin User',
  fullName: 'Admin User',
  email: 'admin@babcock.edu.ng',
  phone: '08012345679',
  role: 'admin',
  isVerified: true,
  avatar: 'https://placehold.co/150x150/e2e8f0/1e293b?text=AD',
  profileImage: 'https://placehold.co/150x150/e2e8f0/1e293b?text=AD',
  ratings: 5,
};

export const EXTRA_USERS: User[] = [
  {
    id: '101',
    name: 'John Seller',
    fullName: 'John Seller',
    email: 'seller@babcock.edu.ng',
    phone: '08012345678',
    role: 'seller',
    isVerified: true,
    avatar: 'https://placehold.co/150x150/e2e8f0/1e293b?text=JS',
    profileImage: 'https://placehold.co/150x150/e2e8f0/1e293b?text=JS',
    ratings: 4.5,
  },
  {
    id: '102',
    name: 'Sarah Smith',
    fullName: 'Sarah Smith',
    email: 'sarah@babcock.edu.ng',
    phone: '08012345681',
    role: 'user',
    isVerified: true,
    avatar: 'https://placehold.co/150x150/e2e8f0/1e293b?text=SS',
    profileImage: 'https://placehold.co/150x150/e2e8f0/1e293b?text=SS',
    ratings: 4.8,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [];

export const MOCK_DISPUTES: Dispute[] = [];
